# docker-compose.yml

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]   # remove this block if no GPU

  ollama-pull:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    command: >
      sh -c "until curl -s -o /dev/null -w '%{http_code}' http://ollama:11434/api/tags | grep -q '200'; do echo 'Waiting for Ollama API...'; sleep 2; done; echo 'Pulling model...'; curl -s -X POST http://ollama:11434/api/pull -d '{\"name\": \"gemma3:4b\"}'"



  chunker:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - ollama
    environment:
      OLLAMA_MODEL: gemma3:4b
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./parsed_docs:/app/parsed_docs

volumes:
  ollama_data: